language: python

python:
  - "2.7"
#Comando para instalar dependencias:
install:
  - sudo apt-get update
  - sudo apt-get install python-setuptools
  - sudo apt-get install python-dev
    apt: name=python-dev state=present
  - sudo apt-get install build-essential
    apt: name=build-essential state=present
  - sudo apt-get install git
    apt: name=git state=present
  - sudo apt-get install pkg-config
    apt: name=pkg-config state=present
  - sudo apt-get install libtiff4-dev
    apt: name=libtiff4-dev state=present
  - sudo apt-get install libjpeg8-dev
    apt: name=libjpeg8-dev state=present
  - sudo apt-get install zlib1g-dev
    apt: name=zlib1g-dev state=present
  - sudo easy_install pip
  - sudo -H pip install Pillow --upgrade
  - shell: sudo pip install -r ~/Eat-with-Rango/requirements.txt

#Comando para ejecutar tests:
script:
  - python manage.py test
