# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 17:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapa',
            name='url',
            field=models.URLField(default=datetime.datetime(2016, 1, 16, 17, 49, 0, 803874, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
